"""Build Windows version resource for PyInstaller EXE metadata."""

from __future__ import annotations

from pathlib import Path

from classroom_library_label_maker.metadata import (
    APP_COMPANY,
    APP_COPYRIGHT,
    APP_DESCRIPTION,
    APP_GUI_EXE_NAME,
    APP_NAME,
    APP_VERSION,
)


def _filevers(version: str) -> tuple[int, int, int, int]:
    parts = [int(p) for p in version.split(".")]
    while len(parts) < 4:
        parts.append(0)
    return parts[0], parts[1], parts[2], parts[3]


def write_version_info(path: Path) -> Path:
    """Write a PyInstaller ``version-file`` for the Windows GUI EXE."""
    major, minor, patch, build = _filevers(APP_VERSION)
    filevers = f"({major}, {minor}, {patch}, {build})"
    prodvers = filevers
    content = f"""# UTF-8
#
# Auto-generated by release_build/write_version_info.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={prodvers},
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'{APP_COMPANY}'),
            StringStruct(u'FileDescription', u'{APP_NAME}'),
            StringStruct(u'FileVersion', u'{APP_VERSION}'),
            StringStruct(u'InternalName', u'{APP_GUI_EXE_NAME}'),
            StringStruct(u'LegalCopyright', u'{APP_COPYRIGHT}'),
            StringStruct(u'OriginalFilename', u'{APP_GUI_EXE_NAME}.exe'),
            StringStruct(u'ProductName', u'{APP_NAME}'),
            StringStruct(u'ProductVersion', u'{APP_VERSION}'),
            StringStruct(u'Comments', u'{APP_DESCRIPTION}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


if __name__ == "__main__":
    target = Path(__file__).resolve().parent / "version_info.txt"
    write_version_info(target)
    print(f"wrote {target}")
